apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kimai2.name" . }}-secret
  labels:
    {{- include "kimai2.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.appSecret }}
  ADMINPASS: {{ .Values.kimaiAdminPassword }}
  DATABASE_URL: {{ include "kimai2.databaseUrl" . }}
